/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package k.colour.java;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAdd(){
        assertEquals(42, Integer.sum(19, 23));
    }
}
